[build]
  command = "npm install --prefix client && npm run build"
  publish = "client/dist"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev --prefix client"
  targetPort = 5173
  publish = "client/dist"
